import type {
  CampaignImpact,
  GrowthAccount,
  GrowthLead,
  GrowthStage,
  SignalSource,
} from "@/types/growth";

const minute = 60_000;
const hour = 60 * minute;
const day = 24 * hour;
const demoNow = Date.UTC(2026, 7, 24, 15, 0);

export const growthAccounts: GrowthAccount[] = [
  {
    id: "northstar-retail",
    name: "Northstar Retail",
    domain: "northstar.example",
    industry: "Retail technology",
    employees: 1280,
    tier: "enterprise",
    stage: "demo",
    intentScore: 91,
    engagementScore: 84,
    adoptionScore: 18,
    buyingGroupCoverage: 75,
    pipelineValue: 180000,
    ltv: 540000,
    owner: "Lina Hassan",
    nextAction: "bookExecutiveDemo",
    members: [
      {
        id: "nora",
        name: "Nora Alami",
        title: "Chief Marketing Officer",
        role: "decisionMaker",
        score: 94,
        email: "nora@northstar.example",
        status: "active",
      },
      {
        id: "sami",
        name: "Sami Kareem",
        title: "Marketing Manager",
        role: "champion",
        score: 88,
        email: "sami@northstar.example",
        status: "active",
      },
      {
        id: "maya",
        name: "Maya Noor",
        title: "Social Media Specialist",
        role: "user",
        score: 79,
        email: "maya@northstar.example",
        status: "active",
      },
      {
        id: "missing-northstar",
        name: "Unassigned",
        title: "Technical evaluator needed",
        role: "technicalEvaluator",
        score: 0,
        email: "",
        status: "missing",
      },
    ],
    signals: [
      {
        id: "ns-1",
        source: "social",
        kind: "socialQuestion",
        occurredAt: demoNow - 18 * minute,
        detail: "Asked about team approval workflows on an Instagram post.",
        postId: "ig-campaign-launch",
      },
      {
        id: "ns-2",
        source: "website",
        kind: "pricingVisit",
        occurredAt: demoNow - 2 * hour,
        detail: "Visited enterprise pricing twice from the same account.",
      },
      {
        id: "ns-3",
        source: "crm",
        kind: "demoRequested",
        occurredAt: demoNow - day,
        detail: "Champion requested a 45-minute workflow demo.",
      },
      {
        id: "ns-4",
        source: "campaign",
        kind: "campaignClick",
        occurredAt: demoNow - 2 * day,
        detail: "Clicked the Arabic customer-story campaign.",
      },
    ],
  },
  {
    id: "crescent-labs",
    name: "Crescent Labs",
    domain: "crescent.example",
    industry: "Professional services",
    employees: 340,
    tier: "midMarket",
    stage: "trial",
    intentScore: 78,
    engagementScore: 72,
    adoptionScore: 61,
    buyingGroupCoverage: 100,
    pipelineValue: 92000,
    ltv: 276000,
    owner: "Omar Saleh",
    nextAction: "inviteSecondAdmin",
    members: [
      {
        id: "layan",
        name: "Layan Fahad",
        title: "VP Marketing",
        role: "decisionMaker",
        score: 81,
        email: "layan@crescent.example",
        status: "active",
      },
      {
        id: "tariq",
        name: "Tariq Amin",
        title: "Growth Lead",
        role: "champion",
        score: 86,
        email: "tariq@crescent.example",
        status: "active",
      },
      {
        id: "reem",
        name: "Reem Adel",
        title: "Content Specialist",
        role: "user",
        score: 73,
        email: "reem@crescent.example",
        status: "active",
      },
      {
        id: "waleed",
        name: "Waleed Sami",
        title: "IT Manager",
        role: "technicalEvaluator",
        score: 54,
        email: "waleed@crescent.example",
        status: "active",
      },
    ],
    signals: [
      {
        id: "cl-1",
        source: "product",
        kind: "postCreated",
        occurredAt: demoNow - 42 * minute,
        detail: "Created the first cross-channel campaign post.",
      },
      {
        id: "cl-2",
        source: "product",
        kind: "trialStarted",
        occurredAt: demoNow - 3 * day,
        detail: "Started a 14-day workspace trial.",
      },
      {
        id: "cl-3",
        source: "email",
        kind: "campaignClick",
        occurredAt: demoNow - 4 * day,
        detail: "Clicked the onboarding checklist email.",
      },
    ],
  },
  {
    id: "masar-logistics",
    name: "Masar Logistics",
    domain: "masar.example",
    industry: "Logistics",
    employees: 810,
    tier: "enterprise",
    stage: "engaged",
    intentScore: 69,
    engagementScore: 63,
    adoptionScore: 0,
    buyingGroupCoverage: 50,
    pipelineValue: 64000,
    ltv: 210000,
    owner: "Dana Fares",
    nextAction: "shareSecurityGuide",
    members: [
      {
        id: "huda",
        name: "Huda Saeed",
        title: "Marketing Director",
        role: "decisionMaker",
        score: 71,
        email: "huda@masar.example",
        status: "active",
      },
      {
        id: "faisal",
        name: "Faisal Rami",
        title: "Digital Marketing Manager",
        role: "champion",
        score: 77,
        email: "faisal@masar.example",
        status: "active",
      },
      {
        id: "missing-masar-user",
        name: "Unassigned",
        title: "Day-to-day user needed",
        role: "user",
        score: 0,
        email: "",
        status: "missing",
      },
      {
        id: "missing-masar-it",
        name: "Unassigned",
        title: "Technical evaluator needed",
        role: "technicalEvaluator",
        score: 0,
        email: "",
        status: "missing",
      },
    ],
    signals: [
      {
        id: "ml-1",
        source: "website",
        kind: "pricingVisit",
        occurredAt: demoNow - 6 * hour,
        detail: "Viewed security and enterprise plan pages.",
      },
      {
        id: "ml-2",
        source: "social",
        kind: "socialQuestion",
        occurredAt: demoNow - day,
        detail: "Asked whether scheduled posts support approvals.",
        postId: "fb-product-tour",
      },
    ],
  },
  {
    id: "namaa-health",
    name: "Namaa Health",
    domain: "namaa.example",
    industry: "Healthcare",
    employees: 2250,
    tier: "enterprise",
    stage: "activated",
    intentScore: 74,
    engagementScore: 80,
    adoptionScore: 82,
    buyingGroupCoverage: 100,
    pipelineValue: 230000,
    ltv: 720000,
    owner: "Lina Hassan",
    nextAction: "resolveSupportBlocker",
    members: [
      {
        id: "amal",
        name: "Amal Riyad",
        title: "Chief Marketing Officer",
        role: "decisionMaker",
        score: 76,
        email: "amal@namaa.example",
        status: "active",
      },
      {
        id: "khaled",
        name: "Khaled Nasser",
        title: "Brand Manager",
        role: "champion",
        score: 84,
        email: "khaled@namaa.example",
        status: "active",
      },
      {
        id: "sara",
        name: "Sara Mahmoud",
        title: "Social Media Lead",
        role: "user",
        score: 89,
        email: "sara@namaa.example",
        status: "active",
      },
      {
        id: "yousef",
        name: "Yousef Adel",
        title: "Security Architect",
        role: "technicalEvaluator",
        score: 67,
        email: "yousef@namaa.example",
        status: "atRisk",
      },
    ],
    signals: [
      {
        id: "nh-1",
        source: "support",
        kind: "supportOpened",
        occurredAt: demoNow - 34 * minute,
        detail: "Admin reported an Instagram reconnect issue.",
      },
      {
        id: "nh-2",
        source: "product",
        kind: "teamInvited",
        occurredAt: demoNow - 5 * hour,
        detail: "Invited three teammates and assigned an approver.",
      },
      {
        id: "nh-3",
        source: "product",
        kind: "postCreated",
        occurredAt: demoNow - 8 * hour,
        detail: "Published five posts across Facebook and Instagram.",
      },
    ],
  },
  {
    id: "vertex-cloud",
    name: "Vertex Cloud",
    domain: "vertex.example",
    industry: "Cloud software",
    employees: 165,
    tier: "smallBusiness",
    stage: "renewal",
    intentScore: 66,
    engagementScore: 58,
    adoptionScore: 47,
    buyingGroupCoverage: 75,
    pipelineValue: 48000,
    ltv: 144000,
    owner: "Omar Saleh",
    nextAction: "launchRenewalReview",
    members: [
      {
        id: "rania",
        name: "Rania Bassam",
        title: "Head of Marketing",
        role: "decisionMaker",
        score: 62,
        email: "rania@vertex.example",
        status: "atRisk",
      },
      {
        id: "jad",
        name: "Jad Nabil",
        title: "Demand Generation Manager",
        role: "champion",
        score: 59,
        email: "jad@vertex.example",
        status: "active",
      },
      {
        id: "mira",
        name: "Mira Samir",
        title: "Content Manager",
        role: "user",
        score: 48,
        email: "mira@vertex.example",
        status: "atRisk",
      },
      {
        id: "missing-vertex",
        name: "Unassigned",
        title: "Technical evaluator needed",
        role: "technicalEvaluator",
        score: 0,
        email: "",
        status: "missing",
      },
    ],
    signals: [
      {
        id: "vc-1",
        source: "crm",
        kind: "renewalViewed",
        occurredAt: demoNow - day,
        detail: "Renewal opportunity entered the 60-day window.",
      },
      {
        id: "vc-2",
        source: "product",
        kind: "postCreated",
        occurredAt: demoNow - 6 * day,
        detail: "Publishing frequency decreased by 38% this month.",
      },
      {
        id: "vc-3",
        source: "support",
        kind: "supportResolved",
        occurredAt: demoNow - 9 * day,
        detail: "Scheduling timezone issue resolved.",
      },
    ],
  },
];

export const growthLeads: GrowthLead[] = growthAccounts.flatMap((account) =>
  account.members
    .filter((member) => member.status !== "missing")
    .map((member) => ({
      id: member.id,
      name: member.name,
      title: member.title,
      accountId: account.id,
      role: member.role,
      score: member.score,
      intent:
        member.score >= 80 ? "high" : member.score >= 60 ? "medium" : "low",
      source: account.signals[0]?.source ?? "crm",
      lastSignal: account.signals[0]?.kind ?? "campaignClick",
      nextAction: account.nextAction,
    })),
);

export const campaignImpact: CampaignImpact[] = [
  {
    id: "arabic-growth",
    name: "Arabic growth playbook",
    channel: "social",
    spend: 18000,
    accounts: 46,
    opportunities: 12,
    pipeline: 410000,
    customers: 5,
    retained: 4,
    ltv: 620000,
  },
  {
    id: "enterprise-webinar",
    name: "Enterprise workflow webinar",
    channel: "campaign",
    spend: 27000,
    accounts: 31,
    opportunities: 15,
    pipeline: 680000,
    customers: 7,
    retained: 7,
    ltv: 1120000,
  },
  {
    id: "activation-nurture",
    name: "Trial activation nurture",
    channel: "email",
    spend: 9500,
    accounts: 58,
    opportunities: 18,
    pipeline: 350000,
    customers: 11,
    retained: 9,
    ltv: 530000,
  },
  {
    id: "customer-stories",
    name: "Customer story retargeting",
    channel: "website",
    spend: 14000,
    accounts: 39,
    opportunities: 10,
    pipeline: 290000,
    customers: 6,
    retained: 6,
    ltv: 470000,
  },
];

export const journeyStages: GrowthStage[] = [
  "discover",
  "engaged",
  "demo",
  "trial",
  "activated",
  "customer",
  "renewal",
];

export const signalSources: SignalSource[] = [
  "website",
  "campaign",
  "social",
  "email",
  "crm",
  "product",
  "support",
];

export const getGrowthAccount = (id: string) =>
  growthAccounts.find((account) => account.id === id);
